### ISSUE TITLE
Issues with unicode characters ° £ €

### ISSUE THREAD

**Issue by IanMercer** [nunit/nunit-transforms#3]
I have `TestCase` attributes that include certain unicode characters like the pound sign, euro and various superscript numbers. In the output these come through in a non-escaped fashion: 

```
 <testcase name="TemperatureCelcius(&quot;19.5 <UNESCAPED CHAR> &quot;)" assertions="1" time="0.023363" status="Passed" classname="NLPTests.TestTemperature" test-case="" />
```

These cannot be read by Visual Studio Online so no test results are shown.

Is there some way to fix the encoding of the file produced, or to translate these characters using the XSLT?

**Comment by CharliePoole** [comment]
@IanMercer Is this issue about the nunit3-junit transform?

**Comment by IanMercer** [comment]
I think so (or at least I was hoping it could be fixed in the transform), but it could possibly be an issue with the output before the transform. Somewhere in the NUnit -> Transform -> Visual Studio Online process it breaks if I put one of those characters in a string in a `TestCase` attribute. Resharper and TeamCity have never had a problem with it (reading the NUnit 3 output).

**Comment by tenwit** [comment]
Try changing the line `<xsl:output method="xml" indent="yes"/>` to `<xsl:output method="html" indent="yes"/>` to see if that helps. I'll see if I can get some tests going in this project (I'm not really au fait with VS/msbuild, this has so fair foiled me).

Apologies for the late response, I've been away-from-internet for quite some time.

**Comment by tenwit** [comment]
I've manually tested the built-in XSLT transformer: none of the output methods change the way unescaped characters above the ASCII character range are handled. I suppose that XSL relies on the fact that XML is supposed to handle unicode cleanly, so if a character is not invalid XML or HTML, it does not modify it.
This most likely means that the problem is with VSO.
You can work around the incompatibility by doing something like what's proposed in this [Stack Overflow answer](http://stackoverflow.com/questions/5482860/xslt-converting-characters-to-their-hexadecimal-unicode-representation). If you get it going, then you might submit a new XSLT file in a new nunit3-vso project :smiley:

**Comment by plmaheu** [comment]
Got this error with an "é" character inside a parametrized test. Also using the xslt transform but I'm on Jenkins.

**Comment by tenwit** [comment]
How does the error manifest itself? Is the XML incorrect, or does the character simply not display correctly in your browser?

I don't know of any way in XSLT 1.0 to transform those sorts of characters to escaped unicode, but as far as I'm aware, transforming them shouldn't be necessary. If it is (for example, if there's a problem in Jenkins' junit xml parser that can't handle non-ascii characters), then we can pull the code from the previously-mentioned stack overflow answer into the XSLT file.

If transforming them is not necessary and the XML being produced is suitable for Jenkins, then you may find that using a different browser helps.

**Comment by IanMercer** [comment]
@tenwit : Visual Studio Online normally displays the test results for a build but when the test results contain Unicode characters all you get is warning messages like this:
![image](https://cloud.githubusercontent.com/assets/347540/24688766/02a1cce8-1977-11e7-89e4-781f5efd020e.png)

**Comment by tenwit** [comment]
Apologies for the late response.
That looks like a problem in the XML parser: those unicode characters are valid and should be viewable in Jenkins or VSO. Since they're not, we'll have to change the xslt to convert those characters to escaped unicode. However I think it would have to be optional, since there's the possibility that other XML parsers won't render the escaped unicode correctly and will handle the unescaped characters.
Unfortunately I'm full-time on non-NUnit projects at the moment and won't be able to work on this for a few months. If anyone else is able to map the unicode characters to their escaped equivalents, it would be much appreciated.

**Comment by CharliePoole** [comment]
I'm closing this without action as it has had no further action for almost three years and this project is about to be archived.
